databases:
  - name: cars-backend
    databaseName: cars_backend
    user: cars_backend_user

services:
  - type: web
    name: rental-back
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cars-backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
